In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available inthe read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/comment-category-prediction-challenge/Sample.csv
/kaggle/input/comment-category-prediction-challenge/train.csv
/kaggle/input/comment-category-prediction-challenge/test.csv


### Data Loading

In [2]:
'''train_df=pd.read_csv('/kaggle/input/comment-category-prediction-challenge/train.csv')
test_df=pd.read_csv('/kaggle/input/comment-category-prediction-challenge/test.csv')
sub=pd.read_csv('/kaggle/input/comment-category-prediction-challenge/Sample.csv')'''

In [3]:
'''from sklearn.ensemble import AdaBoostClassifier,BaggingClassifier,RandomForestClassifier,VotingClassifier'''

In [4]:
'''# =========================
# SINGLE CELL PIPELINE
# =========================

import pandas as pd
import numpy as np
import re
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from scipy.sparse import hstack

# -------------------------
# 1. LOAD DATA
# -------------------------
df = pd.read_csv("/kaggle/input/comment-category-prediction-challenge/train.csv")

# -------------------------
# 2. BASIC CLEANING
# -------------------------
# Drop rows where comment or label is missing
df = df.dropna(subset=["comment", "label"])

# Fill NaNs in categorical columns
categorical_cols = ["race", "religion", "gender", "disability"]
for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

# -------------------------
# 3. TEXT PREPROCESSING
# -------------------------
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)         # remove urls
    text = re.sub(r"@\w+", "", text)            # remove mentions
    text = re.sub(r"[^a-z\s]", "", text)        # keep only letters
    text = re.sub(r"\s+", " ", text).strip()    # remove extra spaces
    return text

df["clean_comment"] = df["comment"].apply(clean_text)

# -------------------------
# 4. TF-IDF VECTORIZATION
# -------------------------
tfidf = TfidfVectorizer(
    max_features=10000,
    ngram_range=(1,2),
    stop_words="english"
)

X_text = tfidf.fit_transform(df["clean_comment"])

# -------------------------
# 5. HANDLE NUMERIC FEATURES
# -------------------------
numeric_cols = [
    "emoticon_1", "emoticon_2", "emoticon_3",
    "upvote", "downvote", "if_1", "if_2"
]

X_numeric = df[numeric_cols].values

# -------------------------
# 6. ENCODE CATEGORICAL FEATURES
# -------------------------
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

X_categorical = df[categorical_cols].values

# -------------------------
# 7. COMBINE ALL FEATURES
# -------------------------
X = hstack([X_text, X_numeric, X_categorical])
y = df["label"]

# -------------------------
# 8. TRAIN TEST SPLIT
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------
# 9. TRAIN LIGHTGBM
# -------------------------
model = lgb.LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    class_weight="balanced", 
    random_state=42
)
model.fit(X_train, y_train)

# -------------------------
# 10. EVALUATION
# -------------------------
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))'''

<>:36: SyntaxWarning: invalid escape sequence '\S'
<>:36: SyntaxWarning: invalid escape sequence '\S'
/tmp/ipykernel_55/2022171215.py:36: SyntaxWarning: invalid escape sequence '\S'
  text = re.sub(r"http\S+", "", text)         # remove urls


'# =========================\n# SINGLE CELL PIPELINE\n# =========================\n\nimport pandas as pd\nimport numpy as np\nimport re\nimport lightgbm as lgb\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.preprocessing import LabelEncoder\nfrom sklearn.metrics import classification_report, confusion_matrix, accuracy_score\nfrom scipy.sparse import hstack\n\n# -------------------------\n# 1. LOAD DATA\n# -------------------------\ndf = pd.read_csv("/kaggle/input/comment-category-prediction-challenge/train.csv")\n\n# -------------------------\n# 2. BASIC CLEANING\n# -------------------------\n# Drop rows where comment or label is missing\ndf = df.dropna(subset=["comment", "label"])\n\n# Fill NaNs in categorical columns\ncategorical_cols = ["race", "religion", "gender", "disability"]\nfor col in categorical_cols:\n    df[col] = df[col].fillna("Unknown")\n\n# -------------------------\n# 3. TEXT PREPROCESSI

In [5]:
'''from sklearn.metrics import f1_score
print("F1_score: ",f1_score(y_test,y_pred,average="macro"))'''

'from sklearn.metrics import f1_score\nprint("F1_score: ",f1_score(y_test,y_pred,average="macro"))'

In [6]:
'''# ==============================
# SUBMISSION CELL (ONE CELL)
# ==============================

import pandas as pd
import numpy as np
from scipy.sparse import hstack

# -------------------------
# 1. LOAD TEST DATA
# -------------------------
test_df = pd.read_csv("/kaggle/input/comment-category-prediction-challenge/test.csv")

# -------------------------
# 2. SAME CLEANING AS TRAIN
# -------------------------
test_df["comment"] = test_df["comment"].fillna("")

# Fill categorical NaNs
categorical_cols = ["race", "religion", "gender", "disability"]
for col in categorical_cols:
    test_df[col] = test_df[col].fillna("Unknown")

# -------------------------
# 3. TEXT CLEANING FUNCTION
# -------------------------
import re
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"[^a-z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

test_df["clean_comment"] = test_df["comment"].apply(clean_text)

# -------------------------
# 4. TF-IDF TRANSFORM (NOT FIT!)
# -------------------------
X_text_test = tfidf.transform(test_df["clean_comment"])

# -------------------------
# 5. NUMERIC FEATURES
# -------------------------
numeric_cols = [
    "emoticon_1", "emoticon_2", "emoticon_3",
    "upvote", "downvote", "if_1", "if_2"
]

X_numeric_test = test_df[numeric_cols].values

# -------------------------
# 6. CATEGORICAL ENCODING
# (must match training encoding!)
# -------------------------
for col in categorical_cols:
    test_df[col] = test_df[col].astype("category").cat.codes

X_categorical_test = test_df[categorical_cols].values

# -------------------------
# 7. COMBINE FEATURES
# -------------------------
X_test_final = hstack([X_text_test, X_numeric_test, X_categorical_test])

# -------------------------
# 8. PREDICT
# -------------------------
test_predictions = model.predict(X_test_final)

# -------------------------
# 9. CREATE SUBMISSION FILE
# -------------------------
n = len(test_predictions)

submission = pd.DataFrame({
    "ID": np.arange(1, n + 1),
    "label": test_predictions
})

submission.to_csv("submission.csv", index=False)

print("✅ submission.csv created successfully!")
print(submission.head())'''

<>:30: SyntaxWarning: invalid escape sequence '\S'
<>:30: SyntaxWarning: invalid escape sequence '\S'
/tmp/ipykernel_55/68281369.py:30: SyntaxWarning: invalid escape sequence '\S'
  text = re.sub(r"http\S+", "", text)


'# ==============================\n# SUBMISSION CELL (ONE CELL)\n# ==============================\n\nimport pandas as pd\nimport numpy as np\nfrom scipy.sparse import hstack\n\n# -------------------------\n# 1. LOAD TEST DATA\n# -------------------------\ntest_df = pd.read_csv("/kaggle/input/comment-category-prediction-challenge/test.csv")\n\n# -------------------------\n# 2. SAME CLEANING AS TRAIN\n# -------------------------\ntest_df["comment"] = test_df["comment"].fillna("")\n\n# Fill categorical NaNs\ncategorical_cols = ["race", "religion", "gender", "disability"]\nfor col in categorical_cols:\n    test_df[col] = test_df[col].fillna("Unknown")\n\n# -------------------------\n# 3. TEXT CLEANING FUNCTION\n# -------------------------\nimport re\ndef clean_text(text):\n    text = text.lower()\n    text = re.sub(r"http\\S+", "", text)\n    text = re.sub(r"@\\w+", "", text)\n    text = re.sub(r"[^a-z\\s]", "", text)\n    text = re.sub(r"\\s+", " ", text).strip()\n    return text\n\ntest_

In [7]:
'''submission'''

'submission'

In [8]:
# =========================
# =========================

import pandas as pd
import numpy as np
import re
import lightgbm as lgb
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
from sklearn.utils.class_weight import compute_class_weight
from scipy.sparse import hstack

# -------------------------
# 1. LOAD DATA
# -------------------------
df = pd.read_csv("/kaggle/input/comment-category-prediction-challenge/train.csv")
df = df.dropna(subset=["comment", "label"])

categorical_cols = ["race", "religion", "gender", "disability"]
for col in categorical_cols:
    df[col] = df[col].fillna("Unknown")

# -------------------------
# 2. TEXT CLEANING
# -------------------------
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

df["clean_comment"] = df["comment"].astype(str).apply(clean_text)

# -------------------------
# 3. WORD TF-IDF
# -------------------------
word_tfidf = TfidfVectorizer(
    max_features=40000,
    ngram_range=(1,2),
    min_df=3,
    max_df=0.9,
    sublinear_tf=True,
    stop_words="english"
)


X_word = word_tfidf.fit_transform(df["clean_comment"])

# -------------------------
# 4. CHARACTER TF-IDF (char_wb = faster)
# -------------------------
char_tfidf = TfidfVectorizer(
    analyzer="char_wb",
    ngram_range=(3,5),
    max_features=25000
)

X_char = char_tfidf.fit_transform(df["clean_comment"])

# -------------------------
# 5. NUMERIC FEATURES
# -------------------------
numeric_cols = [
    "emoticon_1", "emoticon_2", "emoticon_3",
    "upvote", "downvote", "if_1", "if_2"
]

X_numeric = df[numeric_cols].values

# -------------------------
# 6. CATEGORICAL ENCODING
# -------------------------
for col in categorical_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

X_categorical = df[categorical_cols].values

# -------------------------
# 7. COMBINE FEATURES
# -------------------------
X = hstack([X_word, X_char, X_numeric, X_categorical])
y = df["label"]


# -------------------------
# 8. TRAIN TEST SPLIT
# -------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# -------------------------
# 9. CLASS WEIGHTS
# -------------------------
classes = np.unique(y_train)
weights = compute_class_weight("balanced", classes=classes, y=y_train)
class_weights = dict(zip(classes, weights))

# -------------------------
# 10. LIGHTGBM TRAINING (FAST + STRONG)
# -------------------------
model = lgb.LGBMClassifier(
    n_estimators=1200,
    learning_rate=0.03,
    num_leaves=64,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight=class_weights,
    max_bin=255,
    random_state=42,
    n_jobs=-1
)

model.fit(
    X_train,
    y_train,
    eval_set=[(X_test, y_test)],
    eval_metric="multi_logloss",
    callbacks=[
        lgb.early_stopping(100),
        lgb.log_evaluation(100)
    ]
)

# -------------------------
# 11. EVALUATION
# -------------------------
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Macro F1:", f1_score(y_test, y_pred, average="macro"))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 122.445721 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 6052242
[LightGBM] [Info] Number of data points in the train set: 158399, number of used features: 48264
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
[LightGBM] [Info] Start training from score -1.386294
Training until validation scores don't improve for 100 rounds
[100]	valid_0's multi_logloss: 0.361175
[200]	valid_0's multi_logloss: 0.308542
[300]	valid_0's multi_logloss: 0.288325
[400]	valid_0's multi_logloss: 0.277288
[500]	valid_0's multi_logloss: 0.270583
[600]	valid_0's multi_logloss: 0.266209
[700]	valid_0's multi_logloss: 0.263305
[800]	valid_0's multi_logloss: 0.261595
[900]	valid_0's multi_logloss: 0.260715
[1000]	valid_0's multi_logloss: 0.260941
Early stopping, best it

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(


Accuracy: 0.9161111111111111
Macro F1: 0.8303697976854051

Classification Report:

              precision    recall  f1-score   support

           0       0.98      0.94      0.96     22834
           1       0.74      0.85      0.79      3184
           2       0.88      0.90      0.89     12488
           3       0.65      0.71      0.68      1094

    accuracy                           0.92     39600
   macro avg       0.81      0.85      0.83     39600
weighted avg       0.92      0.92      0.92     39600


Confusion Matrix:

[[21547   216   938   133]
 [   38  2719   379    48]
 [  329   680 11230   249]
 [   28    75   209   782]]


In [9]:
import pandas as pd
import numpy as np
from scipy.sparse import hstack

# -------------------------
# 1. LOAD TEST DATA
# -------------------------
test_df = pd.read_csv("/kaggle/input/comment-category-prediction-challenge/test.csv")

# -------------------------
# 2. SAME CLEANING AS TRAIN
# -------------------------
test_df["comment"] = test_df["comment"].fillna("").astype(str)

def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text

test_df["clean_comment"] = test_df["comment"].apply(clean_text)

# Fill categorical
categorical_cols = ["race", "religion", "gender", "disability"]
for col in categorical_cols:
    test_df[col] = test_df[col].fillna("Unknown")

# -------------------------
# 3. TRANSFORM USING TRAINED TF-IDF
# (IMPORTANT: use transform, NOT fit_transform)
# -------------------------
X_word_test = word_tfidf.transform(test_df["clean_comment"])
X_char_test = char_tfidf.transform(test_df["clean_comment"])

# -------------------------
# 4. NUMERIC FEATURES
# -------------------------
numeric_cols = [
    "emoticon_1", "emoticon_2", "emoticon_3",
    "upvote", "downvote", "if_1", "if_2"
]

X_numeric_test = test_df[numeric_cols].values

# -------------------------
# 5. CATEGORICAL ENCODING
# (simple encoding like training)
# -------------------------
for col in categorical_cols:
    test_df[col] = test_df[col].astype("category").cat.codes

X_categorical_test = test_df[categorical_cols].values

# -------------------------
# 6. COMBINE FEATURES
# -------------------------
X_test_final = hstack([X_word_test, X_char_test, X_numeric_test, X_categorical_test])

# -------------------------
# 7. PREDICT
# -------------------------
test_predictions = model.predict(X_test_final)

# -------------------------
# 8. CREATE SUBMISSION
# -------------------------
submission = pd.DataFrame({
    "id": np.arange(1, len(test_predictions) + 1),
    "label": test_predictions
})

submission.to_csv("submission.csv", index=False)

print("✅ submission.csv created successfully!")
print(submission.head())

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/lightgbm/basic.py:1238: UserWarning: Converting data to scipy sparse matrix.
  _log_warning("Converting data to scipy sparse matrix.")


✅ submission.csv created successfully!
   id  label
0   1      2
1   2      2
2   3      0
3   4      0
4   5      2


In [23]:
'submission=pd.read_csv('/kaggle/input/datasets/shubham3421/mlp-project-jan2026-submission/submission.csv')
submission = submission.rename(columns={
    "id": "ID"
})
submission.to_csv("submission.csv", index=False)

print("✅ submission.csv created successfully!")
print(submission.head())'

✅ submission.csv created successfully!
   ID  label
0   1      2
1   2      2
2   3      0
3   4      0
4   5      2
